### ISSUE TITLE
Evaluate automatic data structure generation from schema

### ISSUE THREAD

**Issue by wrznr** [slub/mets-mods2teiHeader#9]
http://www.davekuhlman.org/generateDS.html might be an option to simplify things.

**Comment by wrznr** [comment]
It is not possible to generate a Python data structure for the [TEI all schema](https://www.tei-c.org/release/xml/tei/custom/schema/xsd/tei_all.xsd) via `generateDS` using the most generic invocation:
```shell
(env) $ generateDS -f -o tei.py ~/Downloads/tei_all.xsd
Traceback (most recent call last):
  File "~/env/bin/generateDS", line 10, in <module>
    sys.exit(main())
  File "~/env/bin/generateDS.py", line 8364, in main
    superModule=superModule)
  File "~/env/bin/generateDS.py", line 7787, in parseAndGenerate
    parser.parse(infile)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 282, in CharacterData
  File "~/env/bin/generateDS.py", line 2021, in characters
    curr_value = element.values[-1]
IndexError: list index out of range
```
